### ISSUE TITLE
What is window.ytplayer?

### ISSUE THREAD

**Issue by Jonybang** [harikesh409/Youtube-Downloader-Extension#1]
Hello, what is window.ytplayer object are you using in https://github.com/harikesh409/Youtube-Downloader-Extension/blob/master/src/youtube.js?
Where can i find this package?

**Comment by harikesh409** [comment]
It is a global object provided by YouTube itself. You can try in the console to see all the options in that object.

> Hello, what is window.ytplayer object are you using in https://github.com/harikesh409/Youtube-Downloader-Extension/blob/master/src/youtube.js?
> Where can i find this package?
