### ISSUE TITLE
Can't find the download button

### ISSUE THREAD

**Issue by BrunuhVille** [harikesh409/Youtube-Downloader-Extension#3]
I am using Chrome v88.0 and I can't find the download button after installing the extension
can you give me some guide, like where the button would appear?
Thank you

**Comment by mcfalld** [comment]
I cant find it either

**Comment by ThomasW2005** [comment]
The main doesn't work currently, I already opened a Pull request to fix it, for now you just use the changes

**Comment by bensulli** [comment]
Here's a zip of the fixed unpacked extension based on this PR for those who can't/won't use git - https://drive.google.com/file/d/1e_76Q3uts-Y9i6qPpf0nYgvx6urszKNn/view?usp=sharing

(usual caveats apply of "you shouldn't install things from strangers on the internet").

**Comment by Novack** [comment]
I have found that the extension requires browser restart. Im using Brave.

**Comment by Novack** [comment]
Yes. I installed the extension, tehn reloaded the youtube tab that I had opened. No download button. Restarted the browser and the button was now available.

**Comment by harikesh409** [comment]
@Novack That's the expected behaviour of the browser for any extension.

**Comment by Novack** [comment]
I've been using firefox and recently switched to Brave, so I was not sure. On Firefox, most extensions do not require restart. Sorry to pester.

**Comment by harikesh409** [comment]
> I've been using firefox and recently switched to Brave, so I was not sure. On Firefox, most extensions do not require restart. Sorry to pester.

No problem, just an FYI all chromium based browsers require a restart on new extension installation.
